package com.devlower.vaaz

class DataSource<Plant> {
    val allPlants: MutableList<com.devlower.vaaz.Plant> = mutableListOf(
        Plant("Amaryllis", "Hippeastrum", "The amaryllis are actually hippeastrum bulbous plants. Amaryllis is the common name for these plants, however, it is also the genus for another type of bulb from the same family (Amaryllidaceae) native to South Africa.", "https://www.houseplantsexpert.com/wp-content/uploads/2022/09/hippeastrum-plant.jpg", 23.00, 0.45),
        Plant("African Violet", "Saintpaulia", "Saintpaulia is a genus comprising of approximately 20 species and subspecies, and many varietes. There are a fair few types including standard, trailers, miniatures, and chimeras (a basic way to put them into a category). Various species includes different sizes, flower colors and foliage types.", "https://www.houseplantsexpert.com/wp-content/uploads/2022/09/av-light-purple-1.jpg", 20.00, 0.60),
        Plant("Angel Wing Begonia", "Begonia Coccinea", "Native to South America, these perennial flowering plants (Begonia) grow in sub-tropical and tropical climates, although this species is a hybrid. Fortunately they deal the climate differences and grow in cooler conditions within temperate regions very well.", "https://www.houseplantsexpert.com/wp-content/uploads/2022/08/angel_wing_begonia1.jpg", 18.50, 0.50),
        Plant("Barberton Daisy", "Gerbera Jamesonii", "Native to South Africa this species is a perennial in warmer climates but in cooler countries (temperate regions) it’s grown as an annual and flowering pot plant. There are many varieties and hybrids sold that are more compact in growth than the basic type. The basic type has stalks which grow up to 2ft tall that can become quite lanky and unattractive.", "https://www.houseplantsexpert.com/wp-content/uploads/2022/08/gerbera_jamesonii_1.jpg", 18.50, 0.25),
        Plant("Beach Spider Lily", "Hymenocallis Littoralis", "This amazing bulb based plant “beach spider lily” enjoys environments that are downright aquatic and easy to maintain.", "https://www.houseplantsexpert.com/wp-content/uploads/2022/09/beach_spider_lily_img.jpg", 18.00, 0.45),
        Plant("Belladonna Lily", "Amaryllis Belladonna", "The main characteristics when looking for the differences between these is this species has no leaves at flowering time, solid stems, and produces 6 -12 flowers, while the hippeastrum (amaryllis used for the common name) has leaves shortly after flowering, hollow stems and blooms 3 – 6 flowers.", "https://www.houseplantsexpert.com/wp-content/uploads/2022/09/amaryllis-belladonna.jpg", 21.00, 0.45),
        Plant("Bird Of Paradise", "Strelitzia Reginae", "Strelitzia reginae is a native to the eastern coastlines of southern Africa, where it grows wild in patches that are sometimes miles across. It is sometimes referred to as the Crane plant due to the flowers looking like the feathers on the head of a crane.", "https://www.houseplantsexpert.com/wp-content/uploads/2022/09/Strelitzia_Reginae_Flower_img1.jpg", 26.50, 0.45),
        Plant("Blushing Bromeliad", "Neoregelia Carolinae", "\n" +
                "This native to Brazil bromeliad “from the neoreglia genus” is one of the most commonly grown species indoors from this genus, with the most popular variety being the tricolor. These are also grown outdoors in USDA hardiness zones 10 – 11.", "https://www.houseplantsexpert.com/wp-content/uploads/2022/09/blushing_bromeliad1.jpg", 22.50, 0.60),
        
    )
}